// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Band edges are pinned against IEC 61260-1:2014 as implemented by
// python-acoustics, generated by tools/gen_bands.py.
//
// The value of this test is not that the arithmetic is hard -- it is one power
// of a ratio. It is that the ratio itself is easy to get wrong: the standard
// designs to G = 10^(3/10), not 2, and a base-two implementation is offset from
// every conforming instrument by an error that grows with distance from 1 kHz
// while the plot looks entirely normal. There is no symptom to notice, so it
// has to be asserted.

#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_floating_point.hpp>

#include "rta/dsp/OctaveBands.h"
#include "support/Golden.h"

#include <algorithm>
#include <cmath>
#include <map>
#include <string>

using Catch::Matchers::WithinAbs;
using Catch::Matchers::WithinRel;
using namespace rta::dsp;

namespace {

std::vector<rta::test::GoldenCase> bandGolden() {
    static const auto cases = rta::test::loadGolden(std::string(RTA_GOLDEN_DIR) + "/bands.txt");
    return cases;
}

}  // namespace

TEST_CASE("Band edges match IEC 61260-1:2014", "[bands][golden]") {
    int checked = 0;

    for (const auto& testCase : bandGolden()) {
        if (!testCase.hasRow("center")) continue;
        ++checked;
        CAPTURE(testCase.name);

        const int fraction = (int) testCase.row("fraction").front();
        const int baseCode = (int) testCase.row("base").front();
        const auto base = baseCode == 10 ? OctaveBase::BaseTen : OctaveBase::BaseTwo;

        const auto& indices = testCase.row("index");
        const auto& centres = testCase.row("center");
        const auto& lowers = testCase.row("lower");
        const auto& uppers = testCase.row("upper");

        REQUIRE(indices.size() == centres.size());
        REQUIRE(lowers.size() == centres.size());
        REQUIRE(uppers.size() == centres.size());
        REQUIRE(centres.size() > 4);

        // Limits are set just outside the golden range, which also pins that
        // selection is inclusive of a band sitting exactly at the limit.
        const OctaveBands bands(fraction, centres.front() * 0.999,
                                centres.back() * 1.001, base);

        REQUIRE(bands.size() == centres.size());

        for (std::size_t i = 0; i < bands.size(); ++i) {
            CAPTURE(i, bands[i].index);
            CHECK(bands[i].index == (int) indices[i]);
            CHECK_THAT(bands[i].centre, WithinRel(centres[i], 1.0e-12));
            CHECK_THAT(bands[i].lower, WithinRel(lowers[i], 1.0e-12));
            CHECK_THAT(bands[i].upper, WithinRel(uppers[i], 1.0e-12));
        }
    }

    REQUIRE(checked == 10);
}

TEST_CASE("Base-two differs from base-ten by a growing, signed error", "[bands]") {
    // The standard's stated failure mode, asserted rather than trusted: the two
    // systems agree at the 1 kHz reference and diverge in both directions.
    //
    // Compared by band INDEX, not by position. Over a fixed frequency range the
    // two systems do not even contain the same number of bands -- base-two runs
    // flat at the bottom and sharp at the top, so bands fall off both ends --
    // and pairing them positionally compares band x against band x+1.
    const OctaveBands ten(3, 20.0, 20000.0, OctaveBase::BaseTen);
    const OctaveBands two(3, 20.0, 20000.0, OctaveBase::BaseTwo);

    std::map<int, double> byIndex;
    for (const auto& band : two.bands()) byIndex[band.index] = band.centre;

    auto cents = [](double a, double b) { return 1200.0 * std::log2(b / a); };

    double worstLow = 0.0;
    double worstHigh = 0.0;
    int compared = 0;

    for (const auto& band : ten.bands()) {
        const auto it = byIndex.find(band.index);
        if (it == byIndex.end()) continue;
        ++compared;

        const double delta = cents(band.centre, it->second);
        if (band.centre < 900.0) worstLow = std::min(worstLow, delta);
        if (band.centre > 1100.0) worstHigh = std::max(worstHigh, delta);

        // At the reference itself the two systems must agree exactly.
        if (band.index == 0) CHECK_THAT(delta, WithinAbs(0.0, 1.0e-12));
    }

    REQUIRE(compared > 25);
    CHECK(worstLow < -15.0);   // base-two runs flat below the reference
    CHECK(worstHigh > 10.0);   // and sharp above it
}

TEST_CASE("A band's edges straddle its centre by exactly half a band", "[bands]") {
    for (const int fraction : {1, 3, 6, 12, 24}) {
        CAPTURE(fraction);
        const OctaveBands bands(fraction, 20.0, 20000.0);
        REQUIRE(bands.size() > 4);

        for (const auto& band : bands.bands()) {
            CAPTURE(band.index);
            // Geometric, not arithmetic: the centre sits at sqrt(lower*upper).
            CHECK_THAT(std::sqrt(band.lower * band.upper), WithinRel(band.centre, 1.0e-12));
            // And the width ratio is one band.
            CHECK_THAT(band.upper / band.lower,
                       WithinRel(std::pow(std::pow(10.0, 0.3), 1.0 / fraction), 1.0e-12));
        }
    }
}

TEST_CASE("Neighbouring bands meet without gap or overlap", "[bands]") {
    const OctaveBands bands(3, 20.0, 20000.0);
    for (std::size_t i = 1; i < bands.size(); ++i) {
        CAPTURE(i);
        CHECK_THAT(bands[i].lower, WithinRel(bands[i - 1].upper, 1.0e-12));
    }
}

TEST_CASE("Invalid band fractions are rejected", "[bands]") {
    CHECK_THROWS_AS(OctaveBands(0, 20.0, 20000.0), std::invalid_argument);
    CHECK_THROWS_AS(OctaveBands(-3, 20.0, 20000.0), std::invalid_argument);
    CHECK_THROWS_AS(OctaveBands(3, 20000.0, 20.0), std::invalid_argument);
}
