// SPDX-License-Identifier: AGPL-3.0-or-later
//
// The expectations are NumPy's, generated by tools/gen_golden.py and committed
// under golden/. Asserting that the transform returns what it returned last
// time would freeze whatever it does, including whatever it does wrong; an
// independent implementation disagreeing means one of the two must justify
// itself.

#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_floating_point.hpp>

#include "rta/dsp/Fft.h"
#include "rta/dsp/RealFft.h"
#include "support/Golden.h"

#include <algorithm>
#include <cmath>
#include <complex>
#include <stdexcept>
#include <vector>

using Catch::Matchers::WithinAbs;
using namespace rta::dsp;

namespace {

/// Absolute tolerance scaled to the case's own magnitude.
///
/// A single-precision transform of N points accumulates roughly
/// `eps * sqrt(log2 N)` relative error, so a fixed absolute figure would be
/// far too tight for the 4096-point case and meaninglessly loose for the
/// 16-point one.
double toleranceFor(const std::vector<double>& re, const std::vector<double>& im) {
    double peak = 0.0;
    for (std::size_t i = 0; i < re.size(); ++i) {
        peak = std::max(peak, std::hypot(re[i], im[i]));
    }
    return 1.0e-5 * peak + 1.0e-5;
}

std::vector<rta::test::GoldenCase> golden() {
    static const auto cases = rta::test::loadGolden(std::string(RTA_GOLDEN_DIR) + "/rfft.txt");
    return cases;
}

/// Fetch by name. Selecting by position -- `golden().back()` -- silently picked
/// up an inverse-only case the moment one was appended to the file, and the
/// test failed somewhere unrelated to what it was testing.
rta::test::GoldenCase namedCase(const std::string& name) {
    for (const auto& testCase : golden()) {
        if (testCase.name == name) return testCase;
    }
    throw std::runtime_error("no golden case named " + name);
}

}  // namespace

TEST_CASE("RealFft agrees with NumPy on every golden case", "[fft][golden]") {
    const auto cases = golden();
    REQUIRE(cases.size() >= 8);

    int checked = 0;
    for (const auto& testCase : cases) {
        if (!testCase.hasRow("input")) continue;  // an inverse-only case
        ++checked;
        CAPTURE(testCase.name, testCase.size);

        const auto input = testCase.floatRow("input");
        const auto& expectedRe = testCase.row("rfft_re");
        const auto& expectedIm = testCase.row("rfft_im");

        REQUIRE(input.size() == testCase.size);
        REQUIRE(expectedRe.size() == testCase.size / 2 + 1);
        REQUIRE(expectedIm.size() == testCase.size / 2 + 1);

        RealFft fft(testCase.size);
        std::vector<std::complex<float>> spectrum(fft.numBins());
        fft.forward(input, spectrum);

        const double tol = toleranceFor(expectedRe, expectedIm);

        for (std::size_t bin = 0; bin < spectrum.size(); ++bin) {
            CAPTURE(bin);
            CHECK_THAT((double) spectrum[bin].real(), WithinAbs(expectedRe[bin], tol));
            CHECK_THAT((double) spectrum[bin].imag(), WithinAbs(expectedIm[bin], tol));
        }
    }
    REQUIRE(checked >= 9);
}

TEST_CASE("RealFft inverse recovers the original signal", "[fft]") {
    for (const auto& testCase : golden()) {
        if (!testCase.hasRow("input")) continue;
        CAPTURE(testCase.name);
        const auto input = testCase.floatRow("input");

        RealFft fft(testCase.size);
        std::vector<std::complex<float>> spectrum(fft.numBins());
        std::vector<float> recovered(testCase.size);

        fft.forward(input, spectrum);

        // Without this, a pack/unpack pair that transforms nothing would pass:
        // inverse(forward(x)) == x holds for the identity too.
        double energy = 0.0;
        for (const auto& bin : spectrum) energy += std::abs(bin);
        REQUIRE(energy > 1.0e-3);

        fft.inverse(spectrum, recovered);

        for (std::size_t n = 0; n < input.size(); ++n) {
            CAPTURE(n);
            CHECK_THAT(recovered[n], WithinAbs(input[n], 1.0e-4f));
        }
    }
}

TEST_CASE("Complex Fft round-trips", "[fft]") {
    constexpr std::size_t n = 256;
    std::vector<std::complex<float>> data(n);
    for (std::size_t i = 0; i < n; ++i) {
        data[i] = { std::sin (0.37f * (float) i), std::cos (0.11f * (float) i) };
    }
    const auto original = data;

    Fft fft(n);
    fft.forward(data);

    // A round-trip test on its own cannot tell a correct transform followed by
    // a correct inverse from a pair that do nothing at all -- both satisfy
    // inverse(forward(x)) == x. Assert that forward actually moved the data
    // into some other domain, or this whole case is vacuous.
    double movement = 0.0;
    for (std::size_t i = 0; i < n; ++i) {
        movement += std::abs(data[i] - original[i]);
    }
    REQUIRE(movement > 1.0);

    fft.inverse(data);

    for (std::size_t i = 0; i < n; ++i) {
        CAPTURE(i);
        CHECK_THAT(data[i].real(), WithinAbs(original[i].real(), 1.0e-4f));
        CHECK_THAT(data[i].imag(), WithinAbs(original[i].imag(), 1.0e-4f));
    }
}

TEST_CASE("Complex Fft of a real signal agrees with RealFft", "[fft]") {
    // Two independent code paths that must produce the same numbers. If only
    // one of them is wrong, this catches it without any external reference.
    const auto testCase = namedCase("noise_4096");
    const auto input = testCase.floatRow("input");

    Fft fft(testCase.size);
    std::vector<std::complex<float>> asComplex(testCase.size);
    for (std::size_t i = 0; i < input.size(); ++i) asComplex[i] = { input[i], 0.0f };
    fft.forward(asComplex);

    RealFft realFft(testCase.size);
    std::vector<std::complex<float>> spectrum(realFft.numBins());
    realFft.forward(input, spectrum);

    for (std::size_t bin = 0; bin < spectrum.size(); ++bin) {
        CAPTURE(bin);
        CHECK_THAT(spectrum[bin].real(), WithinAbs(asComplex[bin].real(), 1.0e-2f));
        CHECK_THAT(spectrum[bin].imag(), WithinAbs(asComplex[bin].imag(), 1.0e-2f));
    }
}

TEST_CASE("Sizes that are not a power of two are rejected", "[fft]") {
    CHECK_THROWS_AS(Fft(100), std::invalid_argument);
    CHECK_THROWS_AS(RealFft(100), std::invalid_argument);
    CHECK_THROWS_AS(RealFft(0), std::invalid_argument);
}

TEST_CASE("RealFft inverse matches NumPy on spectra it did not produce", "[fft][golden]") {
    // forward() only ever writes a real value into the DC and Nyquist bins, so
    // round-tripping its own output cannot distinguish an implementation that
    // reads their imaginary part from one that discards it. An analyser edits
    // spectra before inverting -- smoothing, target curves, trace subtraction --
    // and any of those can leave something in an imaginary part that a real
    // signal could never have produced. These cases put it there on purpose.
    int checked = 0;

    for (const auto& testCase : golden()) {
        if (!testCase.hasRow("spec_re")) continue;
        ++checked;
        CAPTURE(testCase.name, testCase.size);

        const auto& specRe = testCase.row("spec_re");
        const auto& specIm = testCase.row("spec_im");
        const auto& expected = testCase.row("irfft");

        REQUIRE(specRe.size() == testCase.size / 2 + 1);
        REQUIRE(specIm.size() == testCase.size / 2 + 1);
        REQUIRE(expected.size() == testCase.size);

        std::vector<std::complex<float>> spectrum(specRe.size());
        for (std::size_t k = 0; k < specRe.size(); ++k) {
            spectrum[k] = { (float) specRe[k], (float) specIm[k] };
        }

        RealFft fft(testCase.size);
        std::vector<float> output(testCase.size);
        fft.inverse(spectrum, output);

        for (std::size_t n = 0; n < output.size(); ++n) {
            CAPTURE(n);
            CHECK_THAT((double) output[n], WithinAbs(expected[n], 1.0e-5));
        }
    }

    REQUIRE(checked == 2);
}
