// SPDX-License-Identifier: AGPL-3.0-or-later
#pragma once

#include <juce_gui_basics/juce_gui_basics.h>

#include "Metrics.h"

namespace az::ui
{

//==============================================================================
// Fonts.
//
// legendFont() is the panel silkscreen face -- set uppercase and tracked out by
// the callers to read like DIN 1451, the typeface actually printed onto touring
// equipment. monoFont() is what every NUMBER (Hz, dB, a countdown) is drawn
// with: digits must not shift width while they count. baseFont() is prose --
// dialog copy, empty states.
//
// ## Why the module does not embed the fonts itself
//
// The obvious implementation is `#include <BinaryData.h>` and reference
// `BinaryData::SairaCondensedSemiBold_ttf` directly. That works in exactly one
// project and quietly fails in the next one, because those symbols are
// generated by one specific `juce_add_binary_data` target from files with those
// exact names. A second project must reproduce the target name, the file names
// and the file set to link at all -- and a project that already has its own
// binary-data target gets a colliding `BinaryData.h`.
//
// So the dependency is inverted: the module states which faces it draws with,
// and the host application hands over the bytes once at startup. Adopting
// az_ui elsewhere then costs one call, not a CMake archaeology session.

/// The five faces the design system draws with. Each blob is a pointer to font
/// file data that must outlive the application -- `juce_add_binary_data` output
/// qualifies, as does anything statically linked.
struct TypefaceSet
{
    struct Blob
    {
        const void* data = nullptr;
        int         size = 0;
    };

    Blob legendSemiBold;  ///< condensed, for tracked uppercase legends
    Blob legendBold;      ///< the heavier legend weight
    Blob body;            ///< prose
    Blob mono;            ///< tabular figures
    Blob monoMedium;      ///< tabular figures, emphasised
};

/// Install the faces. Call once, before the first component is drawn.
///
/// If this is never called the accessors fall back to JUCE's default sans, and
/// assert in a debug build. The fallback exists so a host that forgets still
/// renders something legible; the assertion exists so nobody ships that by
/// accident, because "whatever font this machine happens to have" is not a
/// design, it is a lottery.
void setTypefaces (const TypefaceSet& faces);

[[nodiscard]] juce::Font baseFont   (float height = baseFontSize);
[[nodiscard]] juce::Font monoFont   (float height = baseFontSize, bool medium = false);
[[nodiscard]] juce::Font legendFont (float height = legendFontSize,
                                     bool  bold     = true,
                                     float tracking = trackingColumn);

} // namespace az::ui
