#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Golden vectors for rta_core's FirDesign (lane L7, sub-lane L7-FIR, G10),
plus the MEASURED cepstral oversampling factor plan D6 requires before F2's
C++ constant is fixed. The algorithm reimplementation lives in
tools/gen_fir_algo.py (split out once this file crossed the 400-line cap);
this file is the CLI driver and the golden-file writer.

    .venv/Scripts/python.exe tools/gen_fir.py --out core/tests/golden/fir.txt

Run with the MAIN-CHECKOUT venv (memory/build-toolchain-on-this-machine.md);
this worktree has no scipy. memory/a-gen-script-runs-the-moment-you-invoke-it.md:
a gen_*.py script is a write to the repo the instant Python executes it, so
this one uses argparse for real (copied from tools/gen_mtw.py:165-190) and
`--help` exits before any write.

record docs/dsp/2026-09-06-l7-fir-export.md Sec.4, Sec.7 item 7. Plan
docs/plans/2026-09-07-L7-fir-impl-plan.md task F6, decision D6.
"""

from __future__ import annotations

import argparse
import pathlib
import sys
import tempfile

import numpy as np
from scipy import signal

import gen_fir_algo as algo

NEWLINE = "\n"
FIXTURE_TAPS = [1023, 4095]


def build(out_path: pathlib.Path) -> str:
    lines = [
        "# rta_core golden vectors -- FIR export (lane L7, sub-lane L7-FIR, G10)",
        "# generated by tools/gen_fir.py from numpy.fft.irfft (frequency sampling,",
        "# a second author of core/src/dsp/FirDesign.cpp's own algorithm) and",
        "# scipy.signal.minimum_phase (homomorphic, half=False -- the minimum-phase",
        "# taps, scipy as the second author, record Sec.7 item 7).",
        "# DO NOT EDIT BY HAND. Regenerate and review the diff.",
        "#",
        "# Conventions pinned (record Sec.7, docs/HANDOFF.md's generator-asymmetry",
        "# warning -- FIR taps are ABSOLUTE numbers, not ratios, so every one of",
        "# these must match on both sides):",
        "#   window form:      scipy.signal.get_window(..., fftbins=True) -- PERIODIC,",
        "#                      matching rta::dsp::Window; fftbins=False is the trap.",
        "#   IDFT normalisation: numpy.fft.irfft includes 1/N, matching RealFft::inverse.",
        "#   circular-shift:    build taps[0..(N-1)/2] explicitly, mirror the WINDOWED",
        "#                      value (not the raw sample) to taps[N-1-n].",
        "#   floor:             -120 dB (kMinPhaseFloorDb), multiplicative on |H|.",
        "#   half:              False (scipy) -- |H_min| == |H_lin|, not its square root.",
        "#   normalization:     as_designed (no peak-0dBFS trim baked into these taps).",
        "",
    ]

    sweep_case = ["case fir_oversampling_sweep"]
    chosen_factors: dict[int, int] = {}
    fixture_h_lin: dict[int, np.ndarray] = {}
    fixture_m: dict[int, int] = {}

    for n in FIXTURE_TAPS:
        h_lin, m = algo.design_linear_phase(n)
        fixture_h_lin[n] = h_lin
        fixture_m[n] = m
        table, measured_min = algo.sweep_oversampling_factor(h_lin)
        chosen_factors[n] = measured_min
        loss_by_factor = []
        for factor, _ in table:
            n_fft = algo.next_pow2(factor * n)
            h_min_full, _, _ = algo.homomorphic_reconstruct_full(h_lin, n_fft)
            loss_by_factor.append(algo.truncation_loss_db(h_min_full, n))
        sweep_case.append(f"factors_n{n} " + algo.fmt(f for f, _ in table))
        sweep_case.append(f"residuals_n{n} " + algo.fmt(r for _, r in table))
        sweep_case.append(f"truncation_loss_db_by_factor_n{n} " + algo.fmt(loss_by_factor))
        sweep_case.append(f"measured_minimum_factor_n{n} {measured_min}")
        print(f"  N={n}: measured minimum factor clearing the float32 floor = {measured_min}x "
              f"(residual and truncation-loss both flat across the whole swept range -- "
              f"see gen_fir_algo.sweep_oversampling_factor's docstring)")

    # The single constant the C++ side ships (D6): one step of margin above
    # the measured minimum (algo.factor_with_margin's docstring explains why
    # the bare minimum is not shipped), taken as the max over both fixtures
    # so neither one is left uncovered.
    global_factor = max(algo.factor_with_margin(f) for f in chosen_factors.values())
    sweep_case.append(f"float32_floor {algo.FLOAT32_FLOOR}")
    sweep_case.append(f"chosen_factor_global {global_factor}")
    lines.extend(sweep_case)
    lines.append("end")
    lines.append("")

    for n in FIXTURE_TAPS:
        h_lin = fixture_h_lin[n]
        algo.assert_matches_scipy(h_lin, algo.next_pow2(global_factor * n))

        lines.append(f"case fir_freqsamp_{n}")
        lines.append(f"size {n}")
        lines.append(f"sample_rate {algo.FS}")
        lines.append(f"design_fft_size {fixture_m[n]}")
        lines.append("taps " + algo.fmt(h_lin))
        lines.append("end")
        lines.append("")

        n_fft = algo.next_pow2(global_factor * n)
        h_min_full, _, _ = algo.homomorphic_reconstruct_full(h_lin, n_fft)
        min_taps = h_min_full[:n]
        loss_db = algo.truncation_loss_db(h_min_full, n)

        # scipy as the second author of the minimum-phase TAPS themselves
        # (record Sec.7 item 7) -- called directly, its own floor convention,
        # not gen_fir_algo's reconstruction. The fixture stays clear of
        # -120 dB so the two floors agree; assert_matches_scipy above proves it.
        scipy_taps = signal.minimum_phase(h_lin, method="homomorphic", n_fft=n_fft, half=False)
        cross_check = float(np.max(np.abs(scipy_taps - min_taps)))
        cross_check_peak = max(float(np.max(np.abs(scipy_taps))), 1e-30)
        cross_check_relative = cross_check / cross_check_peak
        print(f"  N={n}: golden vs scipy-own-floor minimum-phase taps, "
              f"max abs diff {cross_check:.3e} (relative {cross_check_relative:.3e})")
        # The two floor CONVENTIONS differ (this project's -120 dB
        # multiplicative floor vs scipy's `1e-7*min(|H|>0)` additive one, D5),
        # so even with the fixture nowhere near either floor the two
        # reconstructions are not bit-identical -- only close, because the
        # floor never actually clamps anything on this fixture. 1e-4 relative
        # catches a real algorithmic disagreement (wrong fold, wrong log
        # base, wrong n_fft) while tolerating that expected floor-choice
        # noise, which measured at ~1e-8 relative for both fixtures.
        if cross_check_relative > 1e-4:
            raise AssertionError(
                f"golden minimum-phase taps (this project's -120 dB floor) disagree with "
                f"scipy's own floor by {cross_check_relative:.3e} relative at N={n} -- this "
                f"is bigger than floor-choice noise, suspect an algorithmic bug")

        lines.append(f"case fir_minphase_{n}")
        lines.append(f"size {n}")
        lines.append(f"sample_rate {algo.FS}")
        lines.append(f"design_fft_size {n_fft}")
        lines.append("taps " + algo.fmt(min_taps))
        lines.append(f"truncation_loss_db {loss_db}")
        lines.append("end")
        lines.append("")

    text = NEWLINE.join(lines) + NEWLINE
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8")
    return text


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                      formatter_class=argparse.RawDescriptionHelpFormatter)
    default_out = pathlib.Path(__file__).resolve().parent.parent / "core" / "tests" / "golden" / "fir.txt"
    parser.add_argument("--out", type=pathlib.Path, default=default_out,
                         help="output path for the golden file")
    parser.add_argument("--check", action="store_true",
                         help="diff a fresh regeneration against --out instead of writing it")
    args = parser.parse_args()

    if args.check:
        with tempfile.TemporaryDirectory() as tmp:
            text = build(pathlib.Path(tmp) / "fir.txt")
            existing = args.out.read_text(encoding="utf-8") if args.out.exists() else None
            if existing == text:
                print(f"{args.out} is byte-identical to a fresh regeneration")
                return 0
            print(f"{args.out} DIFFERS from a fresh regeneration", file=sys.stderr)
            return 1

    build(args.out)
    print(f"wrote {args.out} -- scipy {signal.__name__}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
