#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Golden vector for rta_core's spatialAverage() COMBINE, from scipy spectra.

    .venv/Scripts/python.exe tools/gen_spatial.py --out core/tests/golden/spatial.txt

Writes core/tests/golden/spatial.txt (default path above), committed.
Follows tools/gen_mtw.py's shape (memory/a-gen-script-runs-the-moment-you-
invoke-it.md): real argparse, `--out`, `--help` exits before any write,
`--check` diffs a fresh regeneration instead of overwriting.

The per-position TransferSnapshot already has two independently-authored
goldens (test_transfer_golden.cpp, test_mtw_golden.cpp); re-proving scipy
csd against DualFftEngine here would just commit noise over ground L2/L3
already hold. What has never had a second author is the COMBINE
(docs/dsp/2026-09-06-multichannel-l6b.md §2-§4): three positions' own
H1/coherence from scipy spectra, combined with a fresh reimplementation of
the record's closed forms, never by calling into the C++ side. No
time-domain samples stored: nothing float32 is in this path but the C++
result's own storage (plan task A4, R2).
"""

from __future__ import annotations

import argparse
import pathlib
import sys

import numpy as np
from scipy import signal

FS = 48000.0
N = 1024      # fftSize
HOP = N // 4  # 256
FIFO_DEPTH = 16
# gives EXACTLY 16 frames (frames(n) = 1 + (n-N)//HOP): the whole file IS the
# FIFO's window, so scipy's plain mean and the engine's FIFO mean agree.
N_SAMPLES = N + (FIFO_DEPTH - 1) * HOP  # 4864
NEWLINE = "\n"

GAINS = (1.0, 0.5, 2.0)
DELAYS = (0, 3, 7)
SNR_DB = (40.0, 20.0, 6.0)
TRIMS = (1.0, 2.0, 0.5)  # u_i, the operator weight (§3)

def fmt(values) -> str:
    return " ".join(repr(float(v)) for v in values)


def delayed(x: np.ndarray, delay: int) -> np.ndarray:
    """y[n] = x[n - delay], leading samples zero -- delayedCopy()'s shape."""
    y = np.zeros_like(x)
    if delay > 0:
        y[delay:] = x[:-delay]
    else:
        y[:] = x
    return y


def position_spectra(x: np.ndarray, gain: float, delay: int, snr_db: float, rng) -> tuple:
    """H1 and magnitude-squared coherence for one position, from scipy's own
    csd/welch -- a second author of estimateH1/magnitudeSquaredCoherence."""
    signal_component = gain * delayed(x, delay)
    signal_power = float(np.mean(signal_component ** 2))
    noise_power = signal_power / (10.0 ** (snr_db / 10.0))
    noise = rng.standard_normal(x.size) * np.sqrt(noise_power)
    y = signal_component + noise

    kwargs = dict(fs=FS, window="hann", nperseg=N, noverlap=N - HOP,
                  detrend=False, return_onesided=True, average="mean")
    freqs, sxy = signal.csd(x, y, **kwargs)
    _, sxx = signal.welch(x, **kwargs)
    _, syy = signal.welch(y, **kwargs)

    h = sxy / sxx
    gamma2 = np.clip(np.abs(sxy) ** 2 / (sxx * syy), 0.0, 1.0)
    return freqs, h, gamma2


def combine(hs: list, gamma2s: list, u: tuple) -> tuple:
    """record §2-§4's combine, written independently of
    core/src/dsp/SpatialAverage.cpp -- a second author of the same formula."""
    bins = hs[0].shape[0]
    l_db = np.zeros(bins)
    phase = np.zeros(bins)
    r = np.zeros(bins)
    weighted_coherence = np.zeros(bins)

    for k in range(bins):
        sum_w = 0.0
        sum_u = 0.0
        sum_w_gamma2 = 0.0
        sum_magnitude_term = 0.0
        z = complex(0.0, 0.0)
        for i in range(len(hs)):
            gamma2 = float(gamma2s[i][k])
            w = u[i] * gamma2
            sum_u += u[i]
            sum_w_gamma2 += w
            if w == 0.0:
                continue
            sum_w += w
            h = complex(hs[i][k])
            magnitude = abs(h)
            sum_magnitude_term += w * 20.0 * np.log10(magnitude)
            z += w * (h / magnitude)

        weighted_coherence[k] = (sum_w_gamma2 / sum_u) if sum_u > 0.0 else 0.0
        if sum_w == 0.0:
            continue
        l_db[k] = sum_magnitude_term / sum_w
        zz = z / sum_w
        phase[k] = float(np.angle(zz))
        r[k] = abs(zz)

    return l_db, phase, r, weighted_coherence


def render() -> str:
    # Measured 2026-09-06 on this fixture: gamma2 spans [0.328, 1.000] and R
    # spans [0.219, 1.000] across the three positions and 513 bins, so the
    # weights and the agreement both do real work rather than sitting at 1.
    rng = np.random.default_rng(seed=1906)
    x = rng.standard_normal(N_SAMPLES)

    freqs = None
    hs, gamma2s = [], []
    for gain, delay, snr_db in zip(GAINS, DELAYS, SNR_DB):
        f, h, gamma2 = position_spectra(x, gain, delay, snr_db, rng)
        freqs = f
        hs.append(h)
        gamma2s.append(gamma2)

    l_db, phase, r, weighted_coherence = combine(hs, gamma2s, TRIMS)

    lines = [
        "# rta_core golden vector -- spatial average combine",
        "# generated by tools/gen_spatial.py: scipy spectra per position,",
        "# then an independently-written reimplementation of record",
        "# docs/dsp/2026-09-06-multichannel-l6b.md sections 2-4 for the combine.",
        "# DO NOT EDIT BY HAND. Regenerate and review the diff.",
        "",
        "case spatial_three_positions",
        f"sample_rate {FS!r}",
        f"bin_width_hz {FS / N!r}",
        f"size {hs[0].size}",
        f"u {fmt(TRIMS)}",
        f"freq {fmt(freqs)}",
    ]
    for i in range(len(hs)):
        lines.append(f"h_real_{i} {fmt(hs[i].real)}")
        lines.append(f"h_imag_{i} {fmt(hs[i].imag)}")
        lines.append(f"g2_{i} {fmt(gamma2s[i])}")
    lines.append(f"l_db {fmt(l_db)}")
    lines.append(f"phase {fmt(phase)}")
    lines.append(f"r {fmt(r)}")
    lines.append(f"weighted_coherence {fmt(weighted_coherence)}")
    lines.append("end")
    return NEWLINE.join(lines) + NEWLINE


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    root = pathlib.Path(__file__).resolve().parent.parent
    parser.add_argument("--out", type=pathlib.Path, default=root / "core/tests/golden/spatial.txt",
                         help="output path for the golden file")
    parser.add_argument("--check", action="store_true",
                         help="diff a fresh regeneration against --out instead of writing it")
    args = parser.parse_args()

    if args.check:
        text = render()
        existing = args.out.read_text(encoding="utf-8") if args.out.exists() else None
        if existing == text:
            print(f"{args.out} is byte-identical to a fresh regeneration")
            return 0
        print(f"{args.out} DIFFERS from a fresh regeneration", file=sys.stderr)
        return 1

    text = render()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text, encoding="utf-8")
    print(f"wrote {args.out} -- scipy {signal.__name__}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
