#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Golden vectors for rta_core's auto-EQ / G24 excess-phase kernel (lane L7,
sub-lane L7-EQ). The algorithm reimplementation lives in tools/gen_autoeq_algo.py
(mirrors tools/gen_fir_algo.py's own split); this file is the CLI driver and
the golden-file writer.

    .venv/Scripts/python.exe tools/gen_autoeq.py --out core/tests/golden/autoeq.txt

Run with the MAIN-CHECKOUT venv (memory/build-toolchain-on-this-machine.md);
this worktree has no scipy/numpy of its own. memory/
a-gen-script-runs-the-moment-you-invoke-it.md: a gen_*.py script is a write to
the repo the instant Python executes it, so this one uses argparse for real
(copied from tools/gen_fir.py) and `--help` exits before any write.

Plan docs/plans/2026-09-07-L7-eq-impl-plan.md, Task A (the oversampling-
factor measurement -- this file's ONLY section so far; Task C adds the
ridge-gain-solve section later, appended, not a rewrite).
"""

from __future__ import annotations

import argparse
import pathlib
import sys
import tempfile

import numpy as np

import gen_autoeq_algo as algo

NEWLINE = "\n"


def build(out_path: pathlib.Path) -> str:
    lines = [
        "# rta_core golden vectors -- auto-EQ / G24 excess phase (lane L7, sub-lane L7-EQ)",
        "# generated by tools/gen_autoeq.py from tools/gen_autoeq_algo.py's numpy",
        "# reimplementation of the homomorphic kernel (a second author of",
        "# core/src/dsp/ExcessPhase.cpp and core/src/dsp/MinimumPhase.cpp's own steps).",
        "# DO NOT EDIT BY HAND. Regenerate and review the diff.",
        "#",
        "# Section 1 (Task A): the oversampling-factor MEASUREMENT -- the analytic,",
        "# UNWINDOWED two-path comb H(theta) = 1 + a*e^{-j theta D}, swept over",
        "# F in SWEEP_FACTORS, converged on the RECONSTRUCTED EXCESS-PHASE SWING",
        "# (vs the F=256 reference) and the MIN-PHASE IMPULSE TAIL ENERGY (vs an",
        "# absolute -200 dB floor -- see gen_autoeq_algo.TAIL_CONVERGE_FLOOR_DB for",
        "# why a reference-relative rule fails once double-precision FFT round-trip",
        "# noise dominates). NEVER the magnitude-identity residual: that is an",
        "# algebraic tautology, flat at every factor (gen_fir_algo.py's own finding,",
        "# reused verbatim here since the identity is the same one).",
        "#",
        "# Fixtures are indexed 0..8 in COMB_A_VALUES x COMB_D_SAMPLES order",
        "# (row 'fixture_params_iN a d'); kept in sync by hand with",
        "# core/tests/test_excess_phase.cpp, the same convention",
        "# test_fir_golden.cpp's boostAndCutTarget() uses for gen_fir.py's target.",
        "",
    ]

    sweep = algo.measure_minimum_factor()
    lines.append("case eq_oversampling_sweep")
    lines.append("sweep_factors " + " ".join(str(f) for f in algo.SWEEP_FACTORS))
    lines.append(f"swing_converge_deg {algo.SWING_CONVERGE_DEG}")
    lines.append(f"tail_converge_floor_db {algo.TAIL_CONVERGE_FLOOR_DB}")
    lines.append(f"base_nfft {algo.BASE_NFFT}")

    fixtures = [(a, d) for a in algo.COMB_A_VALUES for d in algo.COMB_D_SAMPLES]
    for i, (a, d) in enumerate(fixtures):
        table = sweep["per_fixture"][(a, d)]
        lines.append(f"fixture_params_i{i} {a} {d}")
        lines.append(f"swings_i{i} " +
                     " ".join(repr(float(table["swings"][f])) for f in algo.SWEEP_FACTORS))
        lines.append(f"tails_i{i} " +
                     " ".join(repr(float(table["tails"][f])) for f in algo.SWEEP_FACTORS))
        lines.append(f"min_factor_i{i} {table['min_factor']}")
        print(f"  fixture {i} (a={a}, D={d}): converged at F={table['min_factor']}x")

    measured_minimum = sweep["measured_minimum"]
    chosen = sweep["chosen_with_margin"]
    lines.append(f"measured_minimum_factor {measured_minimum}")
    lines.append(f"chosen_oversampling_factor {chosen}")
    lines.append("end")
    lines.append("")

    print(f"  measured minimum across all fixtures: {measured_minimum}x")
    print(f"  chosen (one step of margin): {chosen}x -- vs FIR's kCepstralOversamplingFactor=8")
    if chosen <= 8:
        print("  WARNING: chosen factor does not exceed FIR's 8x -- the caveat this task "
              "exists to test would be REFUTED, not proven", file=sys.stderr)

    text = NEWLINE.join(lines) + NEWLINE
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8")
    return text


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                      formatter_class=argparse.RawDescriptionHelpFormatter)
    default_out = pathlib.Path(__file__).resolve().parent.parent / "core" / "tests" / "golden" / "autoeq.txt"
    parser.add_argument("--out", type=pathlib.Path, default=default_out,
                         help="output path for the golden file")
    parser.add_argument("--check", action="store_true",
                         help="diff a fresh regeneration against --out instead of writing it")
    args = parser.parse_args()

    if args.check:
        with tempfile.TemporaryDirectory() as tmp:
            text = build(pathlib.Path(tmp) / "autoeq.txt")
            existing = args.out.read_text(encoding="utf-8") if args.out.exists() else None
            if existing == text:
                print(f"{args.out} is byte-identical to a fresh regeneration")
                return 0
            print(f"{args.out} DIFFERS from a fresh regeneration", file=sys.stderr)
            return 1

    build(args.out)
    print(f"wrote {args.out} -- numpy {np.__version__}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
