#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Golden vectors for rta_core's SpectrumEngine, from scipy.signal.welch.

    .venv/Scripts/python.exe tools/gen_welch.py

Writes core/tests/golden/welch.txt, which is committed.

Why scipy.signal.welch and not our own arithmetic: the whole point of a golden
vector is that it comes from somewhere else. Welch's method has a dozen places
to be subtly wrong -- window normalisation, the factor of two on a one-sided
spectrum, whether DC and Nyquist get that factor, how the last partial segment
is treated -- and each of them produces a plausible-looking spectrum.

Both scalings are emitted:

  density   PSD, units^2/Hz. What a BAND is summed from.
  spectrum  PS, mean square per bin. What a TONE is read from.

They differ by the window's equivalent noise bandwidth, and using the wrong one
for banding reads 1.76 dB high on every broadband source with a Hann window.
"""

from __future__ import annotations

import pathlib
import sys

import numpy as np
from scipy import signal

OUT_DIR = pathlib.Path(__file__).resolve().parent.parent / "core" / "tests" / "golden"
NEWLINE = "\n"
FS = 48000.0


def fmt(values) -> str:
    return " ".join(repr(float(v)) for v in values)


def render(name: str, samples: np.ndarray, nperseg: int, noverlap: int) -> str:
    x = samples.astype(np.float64)
    kwargs = dict(fs=FS, window="hann", nperseg=nperseg, noverlap=noverlap,
                  detrend=False, return_onesided=True, average="mean")
    _, density = signal.welch(x, scaling="density", **kwargs)
    freqs, spectrum = signal.welch(x, scaling="spectrum", **kwargs)

    return NEWLINE.join([
        f"case {name}",
        f"size {samples.size}",
        f"nperseg {nperseg}",
        f"noverlap {noverlap}",
        f"input {fmt(samples)}",
        f"freq {fmt(freqs)}",
        f"density {fmt(density)}",
        f"spectrum {fmt(spectrum)}",
        "end",
    ])


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    blocks = []

    # A sine exactly on a bin centre: `spectrum` must read A^2/2 there.
    n = 4096
    t = np.arange(n)
    sine = (0.5 * np.sin(2 * np.pi * 64 * t / 256)).astype(np.float32)
    blocks.append(render("sine_on_bin", sine, 256, 128))

    # Broadband noise, where `density` is the correct reading and `spectrum`
    # is high by the window's NENBW.
    rng = np.random.default_rng(seed=11)
    noise = (2.0 * rng.standard_normal(8192)).astype(np.float32)
    blocks.append(render("noise_50pct", noise, 512, 256))

    # The same data at 75% overlap: more segments from the same samples, and a
    # different last-segment boundary. Overlap arithmetic is easy to get wrong
    # by one segment, which shifts every value slightly.
    blocks.append(render("noise_75pct", noise, 512, 384))

    # No overlap at all, and a length that is NOT a whole number of segments,
    # so the trailing remainder has to be discarded the same way scipy does.
    blocks.append(render("noise_no_overlap_ragged", noise[:7000], 1024, 0))

    header = [
        "# rta_core golden vectors -- Welch spectra",
        "# generated by tools/gen_welch.py from scipy.signal.welch",
        "# DO NOT EDIT BY HAND. Regenerate and review the diff.",
        "",
    ]
    path = OUT_DIR / "welch.txt"
    path.write_text(NEWLINE.join(header) + NEWLINE.join(blocks) + NEWLINE, encoding="utf-8")
    print(f"wrote {path} -- {len(blocks)} cases, scipy {signal.__name__}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
