#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Generate IEC 61260-1:2014 band definitions for rta_core.

Separate from gen_golden.py because it answers a different question. That script
asks "does our transform compute the same numbers as NumPy"; this one asks "are
our band edges the ones the standard defines". Different reference, different
failure mode, different file.

    .venv/Scripts/python.exe tools/gen_bands.py

Writes core/tests/golden/bands.txt, which is committed.

The octave ratio
----------------
IEC 61260-1:2014 designs to the **base-ten** system, G = 10**(3/10) = 1.995262.
G = 2 exactly is the base-two system: the standard acknowledges it but notes
that the probability of a base-two filter conforming falls as the mid-band
frequency moves away from the 1 kHz reference. Measured, for 1/3 octave, the
base-two centre is 21.9 cents low at 25 Hz and 15.1 cents high at 12.5 kHz.

Both are emitted. Getting this wrong offsets every band from every conforming
instrument while the plot looks entirely normal, so it is pinned rather than
assumed.
"""

from __future__ import annotations

import pathlib
import sys

# python-acoustics predates SciPy's rename of sph_harm to sph_harm_y, and its
# package __init__ imports a module that uses it. The IEC 61260 formulas we want
# do not. Shim, then import -- the alternative is transcribing the standard's
# formulas by hand, which is the very thing an independent reference avoids.
import scipy.special

if not hasattr(scipy.special, "sph_harm"):
    scipy.special.sph_harm = getattr(scipy.special, "sph_harm_y", None)

import acoustics.standards.iec_61260_1_2014 as iec

OUT_DIR = pathlib.Path(__file__).resolve().parent.parent / "core" / "tests" / "golden"

NEWLINE = "\n"


def fmt(values) -> str:
    return " ".join(repr(float(v)) for v in values)


def ratio(base: int) -> float:
    return 10.0 ** (3.0 / 10.0) if base == 10 else 2.0


def render(fraction: int, base: int, indices: range) -> str:
    g = ratio(base)
    half = g ** (1.0 / (2.0 * fraction))

    centres = [iec.REFERENCE_FREQUENCY * g ** (x / fraction) for x in indices]
    lowers = [fc / half for fc in centres]
    uppers = [fc * half for fc in centres]

    lines = [
        f"case bands_base{base}_frac{fraction}",
        f"fraction {fraction}",
        f"base {base}",
        f"index {' '.join(str(x) for x in indices)}",
        f"center {fmt(centres)}",
        f"lower {fmt(lowers)}",
        f"upper {fmt(uppers)}",
        "end",
    ]
    return NEWLINE.join(lines)


def render_nominal() -> str:
    # The labelling frequencies, which are NOT the exact centres: a display
    # reads 31.5 Hz for a band centred on 31.6228 Hz.
    nominal = [float(f) for f in iec.NOMINAL_THIRD_OCTAVE_CENTER_FREQUENCIES]
    return NEWLINE.join([
        "case nominal_third_octave",
        f"nominal {fmt(nominal)}",
        "end",
    ])


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    # Indices span the audio range with a little margin at both ends, so a
    # band-selection bug at the edges has somewhere to show itself.
    coverage = {
        1: range(-6, 5),
        3: range(-18, 14),
        6: range(-36, 27),
        12: range(-72, 53),
        24: range(-144, 105),
    }

    blocks = []
    for fraction, indices in coverage.items():
        for base in (10, 2):
            blocks.append(render(fraction, base, indices))
    blocks.append(render_nominal())

    header = [
        "# rta_core golden vectors -- IEC 61260-1:2014 band definitions",
        "# generated by tools/gen_bands.py from python-acoustics",
        "# DO NOT EDIT BY HAND. Regenerate and review the diff.",
        "",
    ]
    path = OUT_DIR / "bands.txt"
    path.write_text(NEWLINE.join(header) + NEWLINE.join(blocks) + NEWLINE, encoding="utf-8")

    print(f"wrote {path} -- {len(blocks)} cases")
    return 0


if __name__ == "__main__":
    sys.exit(main())
